In [5]:
from sklearn.datasets import load_iris

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline 

In [7]:
dataset=load_iris()

In [8]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [9]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [10]:
df=pd.DataFrame(dataset.data , columns=dataset.feature_names)

In [11]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
df['target']=dataset.target 

In [13]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [14]:
dataset.target 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
## Binary Classification
df_copy=df[df['target']!=2]

Logistic Regression, by default, is meant for binary classification, i.e., it only works when the target variable has two classes (like 0 and 1).

In [16]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

## Independent and dependent features

In [17]:
X= df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [18]:
X 

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [19]:
y 

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int32

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X, y)

LogisticRegression()

In [22]:
# Predicition

y_pred= classifier.predict(X_test)

In [23]:
y_pred 

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [24]:
y_test ==y_pred

83    True
53    True
70    True
45    True
44    True
39    True
22    True
80    True
10    True
0     True
18    True
30    True
73    True
33    True
90    True
4     True
76    True
77    True
12    True
31    True
Name: target, dtype: bool

In [25]:
# confusion matrix , accuracy score , classification report

from sklearn.metrics import confusion_matrix, accuracy_score , classification_report
print(confusion_matrix(y_test,y_pred))
print('----------------------')
print(accuracy_score(y_test,y_pred))
print('----------------------')
print(classification_report(y_test,y_pred))

[[12  0]
 [ 0  8]]
----------------------
1.0
----------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



---

## 🔍 1. **Confusion Matrix**

```python
[[12  0]
 [ 0  8]]
```

This is the confusion matrix for a **binary classification problem**, where:

* Rows = **actual classes** (true labels)
* Columns = **predicted classes** (model's output)

|              | Predicted 0 | Predicted 1 |
| ------------ | ----------- | ----------- |
| **Actual 0** | 12          | 0           |
| **Actual 1** | 0           | 8           |

### 🔹 What this means:

* **True Negatives (TN)** = 12 → Model correctly predicted class 0 for 12 samples.
* **True Positives (TP)** = 8 → Model correctly predicted class 1 for 8 samples.
* **False Positives (FP)** = 0 → No class 0 was incorrectly predicted as class 1.
* **False Negatives (FN)** = 0 → No class 1 was incorrectly predicted as class 0.

✅ **Perfect predictions** — 100% accuracy.

---

## 📈 2. **Accuracy Score**

```python
1.0
```

This means your model correctly predicted **all 20 test samples**.

* **Accuracy = (TP + TN) / Total = (12 + 8) / 20 = 1.0 (or 100%)**

---

## 🧾 3. **Classification Report**

```text
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20
```

Let’s break this down:

| Metric        | Meaning                                                         |
| ------------- | --------------------------------------------------------------- |
| **Precision** | Out of all predicted positives, how many were actually correct? |
| **Recall**    | Out of all actual positives, how many were correctly predicted? |
| **F1-score**  | Harmonic mean of precision and recall (balance between the two) |
| **Support**   | Number of actual occurrences of each class in the test set      |

### Per Class:

* **Class 0:**

  * Precision = 1.00 → all predicted 0s were correct
  * Recall = 1.00 → all actual 0s were found
  * F1-score = 1.00

* **Class 1:**

  * Same — perfect prediction

### Averages:

* **Macro avg**: Unweighted mean of each class's scores
* **Weighted avg**: Mean weighted by support (more representative if classes are imbalanced)

---

## ✅ Final Summary:

* Your logistic regression model **perfectly classified all test data**.
* No false positives or false negatives.
* **But be careful** — this could be:

  * A result of a **simple dataset** (like Iris with just 2 classes).
  * Or possibly **overfitting** if your model is too tightly tuned to training data.

---

Let me know if you'd like help visualizing the confusion matrix or seeing what happens with imperfect predictions.


In [26]:
classifier.predict_proba(X_test)

array([[0.00101197, 0.99898803],
       [0.01462396, 0.98537604],
       [0.00274317, 0.99725683],
       [0.97581217, 0.02418783],
       [0.95442751, 0.04557249],
       [0.9779936 , 0.0220064 ],
       [0.99527478, 0.00472522],
       [0.03030662, 0.96969338],
       [0.9808288 , 0.0191712 ],
       [0.98395142, 0.01604858],
       [0.96565076, 0.03434924],
       [0.96839778, 0.03160222],
       [0.00391076, 0.99608924],
       [0.98981164, 0.01018836],
       [0.00844638, 0.99155362],
       [0.98594633, 0.01405367],
       [0.00188781, 0.99811219],
       [0.00111839, 0.99888161],
       [0.97995345, 0.02004655],
       [0.96983396, 0.03016604]])

The first value is the probability that the sample belongs to class 0.
The second value is the probability that the sample belongs to class 1.

### Hyper parameter tuning

In [27]:
# Grid search cv
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [30]:
params={'penalty':('l1','l2','elasticnet',None),'C':[0.1,1,10,20]}
clf = GridSearchCV(estimator=classifier,param_grid=params,cv=5)

In [31]:
# split into train data to validation data
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [32]:
clf.best_params_

{'C': 0.1, 'penalty': 'l2'}

In [33]:
classifier= LogisticRegression(C=0.1,penalty='l2')
classifier.fit(X_train,y_train)

LogisticRegression(C=0.1)

In [34]:
y_pred=classifier.predict(X_test)

In [35]:
y_pred 

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [36]:
# confusion matrix , accuracy score , classification report

from sklearn.metrics import confusion_matrix, accuracy_score , classification_report
print(confusion_matrix(y_test,y_pred))
print('----------------------')
print(accuracy_score(y_test,y_pred))
print('----------------------')
print(classification_report(y_test,y_pred))

[[12  0]
 [ 0  8]]
----------------------
1.0
----------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Randomized Search cv


In [39]:
from sklearn.model_selection import RandomizedSearchCV

In [47]:
random_clf= RandomizedSearchCV(LogisticRegression(),param_distributions=params,n_iter=20,cv=5)

In [50]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [0.1, 1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [51]:
random_clf.best_params_

{'penalty': 'l2', 'C': 0.1}