In [1]:
# sort , search & counting functions

In [2]:
import numpy as np 

In [3]:
arr= np.array([4,5,6,7,62,78,62,95,45,68,39,81,32,231])

In [4]:
np.sort(arr)

array([  4,   5,   6,   7,  32,  39,  45,  62,  62,  68,  78,  81,  95,
       231])

In [6]:
np.searchsorted(arr,34) # 34 can be inserted on what index in sorted array 

np.int64(4)

In [7]:
arr1 = np.array([0,345,454,0,0,0,1])

In [ ]:
arr1.nonzero() # index of all non zeros

(array([1, 2, 6]),)

In [ ]:
np.count_nonzero(arr1) # count of non zero items

3

In [ ]:
np.where(arr>6) # indexed where value stored is greater than 6

(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]),)

In [ ]:
np.extract(arr>6,arr) # gives value where arr value is greater than 6

array([  7,  62,  78,  62,  95,  45,  68,  39,  81,  32, 231])

In [17]:
# Numpy Byte swapping

In [ ]:
arr.byteswap() # shows byte representation

array([  288230376151711744,   360287970189639680,   432345564227567616,
         504403158265495552,  4467570830351532032,  5620492334958379008,
        4467570830351532032,  6845471433603153920,  3242591731706757120,
        4899916394579099648,  2810246167479189504,  5836665117072162816,
        2305843009213693952, -1801439850948198400])

In [19]:
arr

array([  4,   5,   6,   7,  62,  78,  62,  95,  45,  68,  39,  81,  32,
       231])

In [ ]:
a= np.copy(arr) # deep copy

In [21]:
a

array([  4,   5,   6,   7,  62,  78,  62,  95,  45,  68,  39,  81,  32,
       231])

In [ ]:
b= arr.view() # creates swallow copy

In [23]:
b

array([  4,   5,   6,   7,  62,  78,  62,  95,  45,  68,  39,  81,  32,
       231])

In [24]:
arr

array([  4,   5,   6,   7,  62,  78,  62,  95,  45,  68,  39,  81,  32,
       231])

In [25]:
b[0]=52

In [26]:
b

array([ 52,   5,   6,   7,  62,  78,  62,  95,  45,  68,  39,  81,  32,
       231])

In [28]:
arr

array([ 52,   5,   6,   7,  62,  78,  62,  95,  45,  68,  39,  81,  32,
       231])

In [29]:
# numpy - matrix library

In [30]:
import numpy.matlib as nm 

In [ ]:
nm.zeros(5) # will have atleast 2 dimensions - matrix is a subclass of array

matrix([[0., 0., 0., 0., 0.]])

In [32]:
nm.ones((2,3))

matrix([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [37]:
# Numpy - Linear Algebra

In [39]:
arr_1 = np.random.randint([[2,3],[4,5]])
arr_2 = np.random.randint([[5,3],[2,5]])

🔹 Here’s what happens:
1. low is implicitly 0 (default).
2. high is [[2,3],[4,5]], which is a 2×2 array.
3. NumPy broadcasts this, meaning each element in the output is generated from [0, high[i,j]).

```bash
 [[1 0]
 [2 3]]
```
1 is from [0,2), 0 is from [0,3), 2 is from [0,4), 3 is from [0,5).

In [40]:
arr_1

array([[1, 1],
       [2, 1]], dtype=int32)

In [41]:
arr_2

array([[0, 0],
       [1, 1]], dtype=int32)

In [ ]:
np.dot(arr_1,arr_2) # or aar_1@arr_2

array([[1, 1],
       [1, 1]], dtype=int32)