In [6]:
import numpy as np 

l =[1,2,3,4,5]

In [4]:
ar =np.array(l)

In [5]:
ar

array([1, 2, 3, 4, 5])

1. **Lists** :- ,  Generally slower for numerical operations due to being less optimized for mathematical computations , 
    1.  Operations: Supports a wide range of operations but lacks built-in support for vectorized operations (operations on entire collections at once).
    2. inbuilt 
    3. Operations: Supports a wide range of operations but lacks built-in support for vectorized operations (operations on entire collections at once).

2. **NumPy Arrays** :-  
    1. Homogeneity: Designed to hold items of the same data type, which enables efficient storage and computation
    1. Performance: Optimized for numerical operations, offering significant speed advantages for large datasets. 
    1. Vectorization: Supports element-wise operations, making it easy to perform calculations on entire arrays without explicit loops. 

In [23]:
# Using Vectorization
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition
result = a + b

In [24]:
result

array([5, 7, 9])

In [25]:
# without vectorization

# Create two arrays
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])

# Using a loop to add them
result1 = np.zeros_like(a)
for i in range(len(a)):
    result1[i] = a[i] + b[i]


The line result = np.zeros_like(a) creates a new NumPy array called result that has the same shape and data type as the array a, but with all elements initialized to zero.

In [26]:
result1

array([5, 7, 9])

In [6]:
type(ar)

numpy.ndarray

ndarray :- n dimensional arrays

In [9]:
ar1= np.array([[1,2,3], [4,5,6],  [7,8,9]])

In [10]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(ar1) # here it is a 2 dimensional array

numpy.ndarray

In [27]:
np.asarray([1,2,3])

array([1, 2, 3])

In [28]:
aa= [1,2,3]

In [29]:
np.asanyarray(aa)

array([1, 2, 3])

Here’s a combined explanation of `np.array`, `np.asarray`, and `np.asanyarray`, along with details about masked arrays, formatted for a Jupyter markdown cell:

```markdown
## NumPy Array Creation Functions

In NumPy, the functions `np.array`, `np.asarray`, and `np.asanyarray` are used to create arrays, but they have different behaviors:

### 1. `np.array`
- **Purpose**: Creates a new NumPy array from a given input.
- **Behavior**:
  - Always creates a new array, regardless of whether the input is already a NumPy array.
  - Can specify the desired data type using the `dtype` parameter.
  - Useful when you want to ensure that the output is a NumPy array.
- **Example**:
  ```python
  import numpy as np
  a = [1, 2, 3]
  arr = np.array(a)  # Creates a new NumPy array
  ```

### 2. `np.asarray`
- **Purpose**: Converts the input to an array but returns the original array if the input is already an ndarray.
- **Behavior**:
  - Does not create a copy if the input is already a NumPy array, making it more memory-efficient.
  - Can take other array-like objects (e.g., lists, tuples) and convert them to NumPy arrays.
- **Example**:
  ```python
  import numpy as np
  b = np.array([1, 2, 3])
  arr = np.asarray(b)  # Returns the same array without copying
  ```

### 3. `np.asanyarray`
- **Purpose**: Similar to `np.asarray`, but allows for subclasses of ndarray (like masked arrays).
- **Behavior**:
  - Converts the input to an array but will return subclasses of ndarray as they are (e.g., a masked array remains a masked array).
  - Useful when you want to maintain subclass information while converting.
- **Example**:
  ```python
  import numpy as np
  c = np.ma.array([1, 2, 3])  # Masked array
  arr = np.asanyarray(c)  # Returns the same masked array
  ```

## Masked Arrays

A **masked array** is a special type of array in NumPy that allows for handling invalid or missing data flexibly.

### Key Features:
1. **Masking**:
   - Each element can be "masked" (ignored) based on a corresponding boolean mask. `True` indicates a masked value, and `False` indicates a valid value.
  
2. **Creation**:
   - You can create a masked array using `numpy.ma.array()`, specifying which values to mask.
   - **Example**:
     ```python
     import numpy as np
     data = np.array([1, 2, 3, -999, 5])  # Example data with an invalid value (-999)
     masked_array = np.ma.array(data, mask=(data == -999))
     ```

3. **Operations**:
   - When performing operations, masked values are ignored.
   - **Example**:
     ```python
     mean_value = masked_array.mean()  # Ignores the masked value
     ```

4. **Use Cases**:
   - Useful in data analysis where some values may be missing or invalid, such as in scientific data.

### Example of Masked Array:
```python
import numpy as np

# Create a regular array with some invalid values
data = np.array([1, 2, 3, -999, 5])

# Create a masked array, masking the invalid value
masked_array = np.ma.array(data, mask=(data == -999))

print(masked_array)              # Output: [1 2 3 -- 5] (where -- indicates the masked value)
print(masked_array.mean())       # Output: 2.75 (ignores the masked value)
```

In summary, choose the appropriate function based on whether you need a new array, want to avoid copies, or need to preserve subclass information, and consider using masked arrays for datasets with missing or invalid entries.
```


Behavior of np.asanyarray

    Functionality:
        np.asanyarray converts the input to an array, just like np.asarray.
        However, if the input is already a subclass of ndarray (e.g., a masked array), np.asanyarray will return that subclass without converting it to a base ndarray.

    Use Case:
        This is useful when you want to maintain the properties and methods specific to the subclass. For example, if you have a masked array, using np.asanyarray will ensure that the resulting array retains its masking capabilities

```python
import numpy as np

# Create a masked array
masked_array = np.ma.array([1, 2, 3], mask=[0, 1, 0])  # Masking the second element

# Use np.asanyarray to convert it
result_array = np.asanyarray(masked_array)

# Check the type
print(type(result_array))  # Output: <class 'numpy.ma.core.MaskedArray'>

# Check the masked values
print(result_array)        # Output: [1 -- 3]

```

Comparison with np.asarray

If you had used `np.asarray` instead:
```python result_array_asarray = np.asarray(masked_array)

# Check the type
print(type(result_array_asarray))  # Output: <class 'numpy.ndarray'>
```

In [32]:
# Create a NumPy array
original_array = np.array([1, 2, 3])

# Use np.asarray to create a new variable pointing to the same array
new_array = np.asarray(original_array)

# Modify the original array
original_array[0] = 10

print(original_array)  # Output: [10  2  3]
print(new_array)       # Output: [10  2  3]


[10  2  3]
[10  2  3]


In [35]:
# Create a NumPy array
original_array = np.array([1, 2, 3])

# Use np.array to create a new variable pointing to the same array
new_array = np.array(original_array)

# Modify the original array
original_array[0] = 10

print(original_array)  # Output: [10  2  3]
print(new_array)       # Output: [1  2  3]  


[10  2  3]
[1 2 3]


In [36]:
# Create a masked array
masked_array = np.ma.array([1, 2, 3], mask=[0, 1, 0])  # Masking the second element

# Use np.asanyarray to convert it
result_array = np.asanyarray(masked_array)

# Check the type
print(type(result_array))  # Output: <class 'numpy.ma.core.MaskedArray'>

# Check the masked values
print(result_array)        # Output: [1 -- 3]

<class 'numpy.ma.core.MaskedArray'>
[1 -- 3]


In [37]:
result_array_asarray = np.asarray(masked_array)

# Check the type
print(type(result_array_asarray))  # Output: <class 'numpy.ndarray'>


<class 'numpy.ndarray'>


In [38]:
result_array_asarray

array([1, 2, 3])

In [39]:
result_array

masked_array(data=[1, --, 3],
             mask=[False,  True, False],
       fill_value=999999)

In [40]:
mt = np.matrix(a)

In [41]:
mt

matrix([[1, 2, 3]])

In [43]:
np.asanyarray(mt) # will not convert matrix in array - because matrix is also a form or subset of array

matrix([[1, 2, 3]])

In [44]:
l 

[1, 2, 3, 4, 5]

In [45]:
a = np.array(l)

In [46]:
c=a

In [47]:
c

array([1, 2, 3, 4, 5])

In [48]:
a

array([1, 2, 3, 4, 5])

In [49]:
c[0]=6

In [51]:
c

array([6, 2, 3, 4, 5])

In [ ]:
a # also updated because they are just a reference to the array so both point to same - so it is a swallow copy

array([6, 2, 3, 4, 5])

In [53]:
d = np.copy(a)

In [54]:
d

array([6, 2, 3, 4, 5])

In [55]:
d[1]=9

In [56]:
d

array([6, 9, 3, 4, 5])

In [58]:
a  # now a did not change because we copied the array stored in new space and d points to that so they both point to other object. So it is a deep copy

array([6, 2, 3, 4, 5])

In [74]:
# functions to generate diff type or diff dimensions of array

np.fromfunction(lambda i,j: i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [75]:
np.fromfunction(lambda i,j: i+j , (3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [ ]:
iterable= (i*i for i in range(5))

1. This line creates a generator expression that will yield the squares of numbers from 0 to 4 (i.e., 0, 1, 4, 9, 16).
1. The expression (i * i for i in range(5)) generates values one at a time and does not store them in memory all at once.

A generator expression is a concise way to create an iterator in Python. It generates values on-the-fly as you iterate over them, rather than storing all the values in memory at once. This makes generator expressions more memory-efficient, especially for large datasets.

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

1. The np.fromiter function creates a NumPy array from an iterable (in this case, the generator).
1. The second argument specifies the desired data type of the resulting array, which is float in this case.

In [80]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [2]:
ar = np.array([1,2,3,4])

In [3]:
ar

array([1, 2, 3, 4])

In [5]:
ar.ndim # tells number of dimesnions

1

In [7]:
ar1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
ar1.ndim

2

In [9]:
ar.size

4

In [12]:
ar1.size # number of elements present

12

In [ ]:
ar.shape # first one tells row , 2nd one tells column here only 1 row so showed only 4 columns

(4,)

In [16]:
ar1.shape # here 3 rows and 4 columns

(3, 4)

In [17]:
ar.dtype

dtype('int64')

In [18]:
ar1.dtype

dtype('int64')

In [19]:
np.array([45,65,'sahil']).dtype

dtype('<U21')

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [25]:
list(np.arange(2.3,5.6,.3)) # generate a list from 2.3 to 5.6 with a jump of .3 which we cant do in normal range

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [28]:
np.linspace(1,5,10) # produce 10 data between 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((3,4)) # rows- 3 and cols -4 with all values as zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.zeros((3,4,2)) # we have 3 4*2 matrices

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
ar4 = np.zeros((3,4,2,3)) # we have 4 2*3 matrices and 3 such kind of matrices which contained these 4 matrices

In [ ]:
ar4.ndim # 4 dimensional but cant be visualized

4

In [38]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
on = np.ones((2,3,2))

In [10]:
on 

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
on + 5 # operation on every element

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [12]:
on* 4 # operation on every element

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [18]:
np.empty((3,5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.81019663e-310]])

 when you use `numpy.empty()`, the values inside the newly created array are not set to zero or any default value. Instead, they contain whatever data was already in that memory location (garbage values). Since these values can be random or depend on system state, your program might behave differently each time you run it if you rely on these uninitialized values.

To ensure **reproducible behavior**, you should explicitly set each element of the array to a known value before using it. Otherwise, results might vary unpredictably due to the presence of arbitrary values in the array.

In [ ]:
np.eye(4) # Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [24]:
np.logspace(2,5,10 , base=2) # get the 10 values between 2 to 5 and then perform log on each value by default with base 10

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [46]:
arr= np.random.randn(10000,4) # range - infinity to + infinity , Generates a 3×4 array of random numbers from a standard normal distribution (mean = 0, variance = 1).

STD : it's not exactly zero! But it's very close to zero.

In [47]:
arr 

array([[-0.87946115,  2.61681341,  0.29061346,  1.1855655 ],
       [ 1.90383066, -0.95365352, -0.14081734,  0.24398674],
       [ 0.08279263,  0.93234281,  1.28278711, -0.70546109],
       ...,
       [-0.54936301,  1.56550503,  0.96016046, -0.66428193],
       [ 0.30850947, -0.42162855, -0.29163675,  0.44980786],
       [ 0.56451721,  1.50187944, -0.49006067, -0.36418465]],
      shape=(10000, 4))

In [48]:
import pandas as pd 

In [49]:
df= pd.DataFrame(arr)

In [50]:
df.describe() 

0             1             2             3
count  10000.000000  10000.000000  10000.000000  10000.000000
mean       0.006062      0.003330     -0.014440      0.001959
std        0.997177      1.014535      1.000500      0.995043
min       -3.738587     -3.355284     -3.731704     -3.722936
25%       -0.663077     -0.671111     -0.687787     -0.679960
50%        0.005370      0.015667     -0.015682     -0.001116
75%        0.674241      0.683964      0.653377      0.673766
max        4.334269      3.515425      4.126856      3.566153

In [52]:
arr1= np.random.rand(1000,4) # Range :- 	[0, 1) 

In [53]:
arr1

array([[2.80312363e-01, 9.62015153e-01, 9.57820097e-01, 7.57652147e-01],
       [9.55674082e-01, 7.83394660e-04, 8.02298637e-01, 5.37186207e-01],
       [6.66609823e-01, 2.85216535e-01, 1.20660224e-02, 4.39586592e-01],
       ...,
       [4.59470950e-02, 4.54311122e-01, 9.03911348e-01, 9.58714737e-01],
       [3.58276925e-01, 1.32172927e-01, 5.79785300e-01, 5.63322961e-01],
       [6.52481494e-01, 6.28942652e-01, 4.92185277e-01, 9.48606437e-01]],
      shape=(1000, 4))

In [54]:
df1=pd.DataFrame(arr1)

In [55]:
df1

0         1         2         3
0    0.280312  0.962015  0.957820  0.757652
1    0.955674  0.000783  0.802299  0.537186
2    0.666610  0.285217  0.012066  0.439587
3    0.236570  0.979677  0.007841  0.731121
4    0.068417  0.718542  0.409153  0.440773
..        ...       ...       ...       ...
995  0.797887  0.128715  0.450951  0.943032
996  0.873795  0.787012  0.682307  0.086954
997  0.045947  0.454311  0.903911  0.958715
998  0.358277  0.132173  0.579785  0.563323
999  0.652481  0.628943  0.492185  0.948606

[1000 rows x 4 columns]

In [ ]:
df1.describe() # not as close as to 0 , as the data generated by randn was

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.511085     0.512658     0.490167     0.504353
std       0.293202     0.282405     0.285187     0.290166
min       0.000643     0.000505     0.000110     0.000070
25%       0.256697     0.286918     0.251504     0.249027
50%       0.518484     0.507873     0.482482     0.508778
75%       0.768476     0.751766     0.721429     0.758590
max       0.997810     0.999477     0.999402     0.999036

In [65]:
arr_3= np.random.randint(1,110,(30,40)) # generate from 1 to 110. give a 3*4 matrix

In [70]:
arr_3 

array([[  6,  18,  19, ...,  89,  55,  30],
       [ 47,  92, 109, ...,  16,  57,  37],
       [ 87,   9,   8, ...,  82,  21,  23],
       ...,
       [ 53,  39,  95, ...,  16,  39,  31],
       [ 30,  58,  31, ...,  43,  48,  24],
       [ 39,   2,  66, ...,  16,   2,  42]], shape=(30, 40), dtype=int32)

In [66]:
df2 = pd.DataFrame(arr_3)

In [67]:
df2

0    1    2    3    4    5    6    7    8    9   ...   30   31  32   33  \
0     6   18   19   30   51   90   84   36  106  101  ...   18   90  18   99   
1    47   92  109   42  104   74   71    6  108   49  ...    2  106  74   59   
2    87    9    8   17   70   25   81   51    1   17  ...   80   70  46   99   
3    26   12   27   15   14    2   77    8   26   66  ...  107   66   3   63   
4    39   38  108    5   57   28   35   50   60  106  ...   88   33  77  105   
5    30    5   68   26   19   81   86   64   87   48  ...   57  109   8  101   
6    19   50   80   46   36   94   53   86   76   81  ...   81  105  95   12   
7    99   87  107   41   87   42  100   65   22   29  ...    8   45   9   36   
8    22   56   19   45   92  107   57   96   26   42  ...   31   53  35   71   
9    78   88    4   66   44   63   58  105   28   67  ...   19   90  42  105   
10   34   90   91   38  102  101  108   57   21   89  ...   16   27  63   41   
11   30   76   80   54   77   91   90   22    6   11  ...   36   14  99    2   
12   16   90   94   46   51   39   70   95   31   32  ...   42   15  72   13   
13   86   92  101   83   62   14   45   73    7  103  ...   69   71  16   94   
14   40   84  106   25   57   66   36   32   70   12  ...   48   48  97   45   
15   44   17   34   59   80   11   55  101    3   69  ...   30   17  89   35   
16  102   47  100  101  105    6   67   19   87   83  ...   58   79  71   73   
17  101   95   73   96   85   70   17   96   36   97  ...   15   57  49   44   
18   87   57   65   52   69   10   77   67   15   58  ...   40   73  37   76   
19    9   99  109   29   15   10   16   30   70   12  ...   69   81  36   90   
20   51   84   74   39   73   56   69   38   74  101  ...   12   59  88   52   
21   73   62   47   19   57   47  108   92   67   42  ...   32   19  76   83   
22   59   92   30   83   64    6   70   30   21   87  ...   62   87   1   12   
23   83   93    8   64   61   71   14   25  101  102  ...   18   20  56   61   
24   91   62   77   18   52    2   43   87   30   46  ...   75   48   5   60   
25   89  104   64   39   37   86   73   73   44   56  ...   38   83  72   99   
26   64   63   93   88   68  104  105   11   38  105  ...   34   46  19   23   
27   53   39   95   39   31  107   11   81   10    1  ...  108   23  47   92   
28   30   58   31    2    5   91    9  106    1   17  ...   88   47  32   47   
29   39    2   66   96  102   67   18   39   68   79  ...   42  108  93   61   

     34   35   36   37   38   39  
0    67    8   91   89   55   30  
1   103  104   66   16   57   37  
2    11   69   75   82   21   23  
3    19   64  109   23  104   59  
4     7   35   17   59   48    8  
5    81   53   53   11   10    4  
6    74   29   52   69   32   18  
7    86   11   41   55   83   98  
8     7   84   53    3   61    9  
9    98   71   21   86   70   75  
10    7   34    5   34   30   39  
11   46  105   32   61   15   59  
12   85   98   88   32   87   41  
13   85   60   10  104   19   25  
14   33   59   85   82    4   97  
15   38   19  102   54   69   76  
16   48   63   25   16   60   31  
17   31   28   39   79   84   11  
18   49   36   92   54   40   38  
19   83   48    9   75   14   58  
20   51  104   44   95   82   49  
21    3   50  104   57   32  100  
22   83   27   12    8   40   70  
23   75  100   93   59   41   74  
24   57   62   91   91    1  102  
25   42   93   83   91   19   80  
26   46   70   36   27   98   29  
27   97   18   20   16   39   31  
28  105   33   82   43   48   24  
29   24   49   73   16    2   42  

[30 rows x 40 columns]

In [71]:
np.random.randint(2,10,(3,4))

array([[7, 4, 7, 8],
       [5, 3, 2, 5],
       [8, 2, 8, 3]], dtype=int32)

In [72]:
df2.to_csv('data/export.csv')

In [76]:
arr2 = np.random.rand(3,4)

In [77]:
arr2

array([[0.90358139, 0.39472204, 0.58497185, 0.01012692],
       [0.39321801, 0.08750042, 0.98409923, 0.62219839],
       [0.53993172, 0.19135314, 0.73180126, 0.86658529]])

In [ ]:
arr2.reshape(6,2) # reshape with same data

array([[0.90358139, 0.39472204],
       [0.58497185, 0.01012692],
       [0.39321801, 0.08750042],
       [0.98409923, 0.62219839],
       [0.53993172, 0.19135314],
       [0.73180126, 0.86658529]])

In [88]:
arr2= arr2.reshape(6,-1 ) # reshape with same data -> -1 means that one dimesnion will be self calulated ( can be any negative number  because a dimesnion cant be in negative so auto calculates)

In [91]:
arr2[2:5,1]

array([0.08750042, 0.62219839, 0.19135314])

In [92]:
arr4 = np.random.randint(1,100,(5,5))

In [93]:
arr4

array([[28, 31, 64,  3, 53],
       [20, 85,  4, 93, 41],
       [94, 35, 53, 28, 96],
       [45, 27, 66, 27, 12],
       [38, 26, 63, 64, 23]], dtype=int32)

In [94]:
arr4>50

array([[False, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False, False,  True, False, False],
       [False, False,  True,  True, False]])

In [96]:
arr4[arr4>50]

array([64, 53, 85, 93, 94, 53, 96, 66, 63, 64], dtype=int32)

In [99]:
arr4[2:4,[1,2]]

array([[35, 53],
       [27, 66]], dtype=int32)

In [100]:
arr4[0][0]=220

In [101]:
arr4

array([[220,  31,  64,   3,  53],
       [ 20,  85,   4,  93,  41],
       [ 94,  35,  53,  28,  96],
       [ 45,  27,  66,  27,  12],
       [ 38,  26,  63,  64,  23]], dtype=int32)

In [113]:
ar_1 = np.random.randint(1,3,(3,3))
ar_2 = np.random.randint(1,3,(3,3))

In [114]:
ar_1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]], dtype=int32)

In [115]:
ar_2

array([[2, 2, 1],
       [1, 2, 1],
       [1, 2, 2]], dtype=int32)

In [116]:
ar_1 + ar_2

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 4]], dtype=int32)

In [117]:
ar_1-ar_2

array([[-1, -1,  1],
       [ 1, -1,  1],
       [ 1, -1,  0]], dtype=int32)

In [118]:
ar_1/ar_2

array([[0.5, 0.5, 2. ],
       [2. , 0.5, 2. ],
       [2. , 0.5, 1. ]])

In [ ]:
ar_1*ar_2 # index wise multiplication

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 4]], dtype=int32)

In [ ]:
# matrix multiplication
# let dimension of a array m1=  m *n
# dimesnion of other array m2=  p* a

# condition column of first matrix m1 must be equal to rows of 2nd matrix m2
# so n=p

In [ ]:
ar_1@ar_2 # performs matrix multiplication

array([[ 5,  8,  6],
       [ 7, 10,  7],
       [ 7, 10,  7]], dtype=int32)

In [124]:
ar_1 + 10 # add 10 in each element

array([[11, 11, 12],
       [12, 11, 12],
       [12, 11, 12]], dtype=int32)

In [126]:
ar_1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]], dtype=int32)

In [127]:
ar_1**2

array([[1, 1, 4],
       [4, 1, 4],
       [4, 1, 4]], dtype=int32)

In [129]:
# numpy broadcasting
ar_3= np.zeros((4,4))

In [135]:
ar_3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [132]:
row = np.array([1,2,3,4])

In [133]:
row

array([1, 2, 3, 4])

In [ ]:
ar_3 + row # if added a list  then it ADDS LINEARLY ( row by row , row by row)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
# to add column wise
ar_3 + row.T # this was 1 dimensional so wont transponse atleast 2d is required

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [141]:
col = np.array([[1,2,3,4]])

In [143]:
col # 1 row and 1 column

array([[1, 2, 3, 4]])

In [144]:
col.ndim

2

In [ ]:
col.T # transpose

array([[1],
       [2],
       [3],
       [4]])

In [149]:
col 

array([[1, 2, 3, 4]])

In [ ]:
col.transpose() # or this way

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
ar_3 + col.T  # added column wise

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [156]:
arr4

array([[220,  31,  64,   3,  53],
       [ 20,  85,   4,  93,  41],
       [ 94,  35,  53,  28,  96],
       [ 45,  27,  66,  27,  12],
       [ 38,  26,  63,  64,  23]], dtype=int32)