In [ ]:
# numpy array manipulation

In [1]:
import numpy as np 

In [3]:
arr = np.random.randint(1,10,(3,4))

In [13]:
arr 

array([[3, 1, 6, 1],
       [6, 5, 5, 4],
       [1, 5, 1, 4]], dtype=int32)

In [4]:
arr.reshape(6,2)

array([[3, 1],
       [6, 1],
       [6, 5],
       [5, 4],
       [1, 5],
       [1, 4]], dtype=int32)

In [5]:
arr.T 

array([[3, 6, 1],
       [1, 5, 5],
       [6, 5, 1],
       [1, 4, 4]], dtype=int32)

In [6]:
arr.flatten() # converts to 1 dimensional

array([3, 1, 6, 1, 6, 5, 5, 4, 1, 5, 1, 4], dtype=int32)

In [7]:
arr1 = np.array([1,2,3,3,4])

In [8]:
arr1.ndim

1

In [ ]:
np.expand_dims(arr1 ,axis=1) # converts to 2 dimnsional across axis=1 ( column)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [ ]:
np.expand_dims(arr1 ,axis=0) # converts to 2d across row ( axis=0)

array([[1, 2, 3, 3, 4]])

In [14]:
data= np.array([[1],[2],[3]])

In [15]:
data 

array([[1],
       [2],
       [3]])

In [16]:
np.squeeze(data) 

array([1, 2, 3])

In [ ]:
np.squeeze

In [29]:
data1 = np.array([[[1, 2, 3]], [[4, 5, 6]]])  # Shape (2, 1, 3)
squeezed_data = np.squeeze(data1)

print(squeezed_data.shape)  # Output: (2, 3)
print(squeezed_data)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [30]:
data1 

array([[[1, 2, 3]],

       [[4, 5, 6]]])

When to Use squeeze()?

✅ Removing unnecessary dimensions (e.g., after using np.expand_dims() or reshaping).
✅ Working with ML models (e.g., when output shape is (1, N) but you need (N,)).
✅ Processing grayscale images in shape (1, H, W) → Convert to (H, W).

1. 💡 If there's no axis of size 1, squeeze() does nothing.
2. If an array has dimensions with size 1 (e.g., shape=(3,1,4), shape=(1,5,1), etc.), np.squeeze() removes them.
3. You can remove a particular axis using axis parameter:


data = np.array([[[1], [2], [3]]])  # Shape (1, 3, 1)
squeezed_data = np.squeeze(data, axis=0)  # Remove only axis 0

print(squeezed_data.shape)  # Output: (3,1) - Axis 0 is removed, but (3,1) remains


like list in a list or array in array with single element then it will squeeze but if multiple element then do nothing

In [31]:
arr1 

array([1, 2, 3, 3, 4])

In [ ]:
np.repeat(arr1,3) # repeat the elements three time

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [ ]:
arr1  

array([1, 2, 3, 3, 4])

In [36]:
np.roll(arr1,2) # every data is shifted by 2 places - 0 index : 0+2 , 4th index :- 4+2 %5 :- 1st index

array([3, 4, 1, 2, 3])

In [ ]:
np.diag(arr1) # place the data on diagonal

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [38]:
# numpy binary operations

In [41]:
arr2= np.random.randint(1,10,(3,4))

In [42]:
arr2

array([[4, 8, 4, 5],
       [1, 8, 7, 4],
       [3, 9, 1, 7]], dtype=int32)

In [44]:
arr

array([[3, 1, 6, 1],
       [6, 5, 5, 4],
       [1, 5, 1, 4]], dtype=int32)

In [ ]:
arr + arr2  # index wise

array([[ 7,  9, 10,  6],
       [ 7, 13, 12,  8],
       [ 4, 14,  2, 11]], dtype=int32)

In [49]:
arr 

array([[3, 1, 6, 1],
       [6, 5, 5, 4],
       [1, 5, 1, 4]], dtype=int32)

In [50]:
~arr

array([[-4, -2, -7, -2],
       [-7, -6, -6, -5],
       [-2, -6, -2, -5]], dtype=int32)

In [57]:
arr3= np.array(['sahil dhillon','ankit'])

In [58]:
arr3

array(['sahil dhillon', 'ankit'], dtype='<U13')

In [59]:
np.char.upper(arr3)

array(['SAHIL DHILLON', 'ANKIT'], dtype='<U13')

In [60]:
np.char.title(arr3)

array(['Sahil Dhillon', 'Ankit'], dtype='<U13')

In [61]:
np.char.capitalize(arr3)

array(['Sahil dhillon', 'Ankit'], dtype='<U13')

In [62]:
np.sin(arr)

array([[ 0.14112001,  0.84147098, -0.2794155 ,  0.84147098],
       [-0.2794155 , -0.95892427, -0.95892427, -0.7568025 ],
       [ 0.84147098, -0.95892427,  0.84147098, -0.7568025 ]])

In [69]:
np.cos(arr) 

array([[-0.9899925 ,  0.54030231,  0.96017029,  0.54030231],
       [ 0.96017029,  0.28366219,  0.28366219, -0.65364362],
       [ 0.54030231,  0.28366219,  0.54030231, -0.65364362]])

In [70]:
np.exp(arr)

array([[ 20.08553692,   2.71828183, 403.42879349,   2.71828183],
       [403.42879349, 148.4131591 , 148.4131591 ,  54.59815003],
       [  2.71828183, 148.4131591 ,   2.71828183,  54.59815003]])

In [71]:
np.power(arr,2)

array([[ 9,  1, 36,  1],
       [36, 25, 25, 16],
       [ 1, 25,  1, 16]], dtype=int32)

In [72]:
np.mean(arr1)

np.float64(2.6)

In [76]:
np.median(arr1)

np.float64(3.0)

In [78]:
np.std(arr1)

np.float64(1.019803902718557)

In [79]:
np.var(arr1)

np.float64(1.0400000000000003)

In [80]:
np.min(arr)

np.int32(1)